title: <p align="center"> Talal El-Houni </p>
logo: "/images/picofme.png?raw=true" 
description: > 
  <p align="justify">
  MSc in Health Data Science, skilled in Python and SQL, turning data into strategic insights in healthcare and market research. 
  <br><br>
  Driven by the potential of technology to improve lives, ready for fresh challenges with a mix of analytical prowess and creative problem-solving.
  </p>
  <br><br>
  <a href="https://www.linkedin.com/in/talal-e-abb417276/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 
